In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [4]:
data = pd.read_csv('data/Airline_Delay_Cause.csv')

In [6]:
data

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",136.0,7.0,5.95,0.00,...,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",91.0,16.0,7.38,0.00,...,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",19.0,2.0,0.13,0.00,...,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,14.0,7.26,0.76,...,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",181.0,19.0,13.84,0.00,...,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,2003,6,DL,Delta Air Lines Inc.,SEA,"Seattle, WA: Seattle/Tacoma International",480.0,84.0,25.69,3.09,...,0.0,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,2003,6,DL,Delta Air Lines Inc.,SFO,"San Francisco, CA: San Francisco International",505.0,111.0,21.78,2.24,...,0.0,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,2003,6,DL,Delta Air Lines Inc.,SJC,"San Jose, CA: Norman Y. Mineta San Jose Intern...",146.0,36.0,6.99,0.00,...,0.0,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,2003,6,DL,Delta Air Lines Inc.,SJU,"San Juan, PR: Luis Munoz Marin International",95.0,13.0,3.66,0.00,...,0.0,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,2003,6,DL,Delta Air Lines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",3466.0,454.0,121.15,7.61,...,1.0,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [8]:
data.dropna(inplace=True)

In [10]:
data

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",136.0,7.0,5.95,0.00,...,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",91.0,16.0,7.38,0.00,...,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",19.0,2.0,0.13,0.00,...,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,14.0,7.26,0.76,...,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",181.0,19.0,13.84,0.00,...,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,2003,6,DL,Delta Air Lines Inc.,SEA,"Seattle, WA: Seattle/Tacoma International",480.0,84.0,25.69,3.09,...,0.0,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,2003,6,DL,Delta Air Lines Inc.,SFO,"San Francisco, CA: San Francisco International",505.0,111.0,21.78,2.24,...,0.0,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,2003,6,DL,Delta Air Lines Inc.,SJC,"San Jose, CA: Norman Y. Mineta San Jose Intern...",146.0,36.0,6.99,0.00,...,0.0,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,2003,6,DL,Delta Air Lines Inc.,SJU,"San Juan, PR: Luis Munoz Marin International",95.0,13.0,3.66,0.00,...,0.0,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,2003,6,DL,Delta Air Lines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",3466.0,454.0,121.15,7.61,...,1.0,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [14]:
data.columns

Index(['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name',
       'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [24]:
Y = data['carrier']

In [26]:
Y

0         9E
1         9E
2         9E
3         9E
4         9E
          ..
318012    DL
318013    DL
318014    DL
318015    DL
318016    DL
Name: carrier, Length: 317261, dtype: object

In [28]:
Y.value_counts()

carrier
OO    38038
DL    27518
EV    26564
MQ    24378
AA    19770
UA    19096
WN    17576
YV    14483
AS    12933
F9    12275
9E    11943
OH    11902
B6    11572
US    10692
NW     8061
XE     7366
FL     6955
CO     6908
G4     6369
YX     4425
RU     4134
NK     3788
HA     3579
DH     1923
HP     1579
VX     1425
TZ      918
QX      838
AQ      253
Name: count, dtype: int64

In [30]:
X = data[['arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay']]

In [32]:
X

,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,136.0,7.0,5.95,0.00,0.05,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,91.0,16.0,7.38,0.00,2.54,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,19.0,2.0,0.13,0.00,1.00,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,88.0,14.0,7.26,0.76,4.35,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,181.0,19.0,13.84,0.00,3.07,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,480.0,84.0,25.69,3.09,33.96,0.0,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,505.0,111.0,21.78,2.24,73.81,0.0,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,146.0,36.0,6.99,0.00,26.85,0.0,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,95.0,13.0,3.66,0.00,7.92,0.0,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,3466.0,454.0,121.15,7.61,221.91,1.0,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [34]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317261 entries, 0 to 318016
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   arr_flights          317261 non-null  float64
 1   arr_del15            317261 non-null  float64
 2   carrier_ct           317261 non-null  float64
 3   weather_ct           317261 non-null  float64
 4   nas_ct               317261 non-null  float64
 5   security_ct          317261 non-null  float64
 6   late_aircraft_ct     317261 non-null  float64
 7   arr_cancelled        317261 non-null  float64
 8   arr_diverted         317261 non-null  float64
 9   arr_delay            317261 non-null  float64
 10  carrier_delay        317261 non-null  float64
 11  weather_delay        317261 non-null  float64
 12  nas_delay            317261 non-null  float64
 13  security_delay       317261 non-null  float64
 14  late_aircraft_delay  317261 non-null  float64
dtypes: float64(15)
memory usage: 38.7 MB

In [38]:
Data = data[data['carrier'].isin(['OO','DL'])]

In [40]:
Data

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
352,2022,5,DL,Delta Air Lines Inc.,ABQ,"Albuquerque, NM: Albuquerque International Sun...",93.0,12.0,6.64,1.00,...,0.00,4.25,2.0,0.0,429.0,218.0,49.0,4.0,0.0,158.0
353,2022,5,DL,Delta Air Lines Inc.,ALB,"Albany, NY: Albany International",93.0,28.0,16.07,0.00,...,0.00,5.87,5.0,0.0,1374.0,602.0,0.0,199.0,0.0,573.0
354,2022,5,DL,Delta Air Lines Inc.,ANC,"Anchorage, AK: Ted Stevens Anchorage Internati...",215.0,25.0,17.90,0.00,...,0.00,4.16,2.0,1.0,958.0,676.0,0.0,63.0,0.0,219.0
355,2022,5,DL,Delta Air Lines Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",18297.0,2573.0,1012.39,95.51,...,0.52,963.54,444.0,23.0,193784.0,102534.0,7741.0,19640.0,34.0,63835.0
356,2022,5,DL,Delta Air Lines Inc.,ATW,"Appleton, WI: Appleton International",31.0,3.0,2.00,0.00,...,0.00,0.00,0.0,0.0,109.0,89.0,0.0,20.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,2003,6,DL,Delta Air Lines Inc.,SEA,"Seattle, WA: Seattle/Tacoma International",480.0,84.0,25.69,3.09,...,0.00,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,2003,6,DL,Delta Air Lines Inc.,SFO,"San Francisco, CA: San Francisco International",505.0,111.0,21.78,2.24,...,0.00,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,2003,6,DL,Delta Air Lines Inc.,SJC,"San Jose, CA: Norman Y. Mineta San Jose Intern...",146.0,36.0,6.99,0.00,...,0.00,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,2003,6,DL,Delta Air Lines Inc.,SJU,"San Juan, PR: Luis Munoz Marin International",95.0,13.0,3.66,0.00,...,0.00,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,2003,6,DL,Delta Air Lines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",3466.0,454.0,121.15,7.61,...,1.00,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [42]:
Data['carrier'].value_counts()

carrier
OO    38038
DL    27518
Name: count, dtype: int64

In [44]:
y = Data['carrier']
x = Data[['arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay']]

In [46]:
y

352       DL
353       DL
354       DL
355       DL
356       DL
          ..
318012    DL
318013    DL
318014    DL
318015    DL
318016    DL
Name: carrier, Length: 65556, dtype: object

In [48]:
x

,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
352,93.0,12.0,6.64,1.00,0.10,0.00,4.25,2.0,0.0,429.0,218.0,49.0,4.0,0.0,158.0
353,93.0,28.0,16.07,0.00,6.06,0.00,5.87,5.0,0.0,1374.0,602.0,0.0,199.0,0.0,573.0
354,215.0,25.0,17.90,0.00,2.94,0.00,4.16,2.0,1.0,958.0,676.0,0.0,63.0,0.0,219.0
355,18297.0,2573.0,1012.39,95.51,501.03,0.52,963.54,444.0,23.0,193784.0,102534.0,7741.0,19640.0,34.0,63835.0
356,31.0,3.0,2.00,0.00,1.00,0.00,0.00,0.0,0.0,109.0,89.0,0.0,20.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,480.0,84.0,25.69,3.09,33.96,0.00,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,505.0,111.0,21.78,2.24,73.81,0.00,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,146.0,36.0,6.99,0.00,26.85,0.00,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,95.0,13.0,3.66,0.00,7.92,0.00,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,3466.0,454.0,121.15,7.61,221.91,1.00,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [50]:
y.value_counts()

carrier
OO    38038
DL    27518
Name: count, dtype: int64

In [54]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(x,y,test_size=0.20 , random_state=44 , shuffle=True)
print("X_train shape = ",X_train.shape)
print("X_test shape = ",X_test.shape)
print("Y_train shape = ",Y_train.shape)
print("Y_test shape = ",Y_test.shape)

X_train shape =  (52444, 15)
X_test shape =  (13112, 15)
Y_train shape =  (52444,)
Y_test shape =  (13112,)

In [56]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
randomforestclassifiermodel = RandomForestClassifier(criterion='gini' , n_estimators=100 , max_depth=2 , random_state=33)

In [60]:
randomforestclassifiermodel.fit(X_train ,Y_train)

RandomForestClassifier(max_depth=2, random_state=33)

In [62]:
y_pred = randomforestclassifiermodel.predict(X_test)

In [64]:
y_pred

array(['DL', 'OO', 'OO', ..., 'OO', 'OO', 'DL'], dtype=object)

In [66]:
from sklearn.metrics import classification_report

In [72]:
ClassificationReports = classification_report(Y_test,y_pred)
print('Classification Report is : \n', ClassificationReports)

Classification Report is :
               precision    recall  f1-score   support

          DL       0.70      0.45      0.55      5447
          OO       0.69      0.86      0.77      7665

    accuracy                           0.69     13112
   macro avg       0.70      0.66      0.66     13112
weighted avg       0.69      0.69      0.68     13112